config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  get 'home/index'
  root 'home#index'
  get "video", to: "home#video"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title,  presence: true
  validates :description, presence: true, length: { :minimum => 5 }
  #creating relationship
  belongs_to :user
  def to_s
    title
  end
  has_rich_text :description
end
# for looking better

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
         
  def to_s
  email
end

has_many :courses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #authentication user
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    #adding code for the search
    if params[:title]
      @courses = Course.where('title ILIKE ?', "%#{params[:title]}%")
    else
      @courses = Course.all
    end  
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    #user automatically assigned as the current user to create a course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.all.limit(3)
    @recent_couses = Course.all.limit(3).order(created_at: :desc)
  end

  def video
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.row.row-cols-2.row-cols-md-4.g-4
  .col
    .card
      .card-header
        .fa.fa-book
        = link_to course.title, course_path(course)
      .card-body
        = course.description
      .card-footer
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
        .row
        .fa.fa-chalkboard-teacher
        = course.user
      .card-footer
        = link_to 'Show', course, class: 'btn btn-sm btn-warning'
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
        = link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-warning'

app/views/courses/_form.html.haml
.container
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .field
    = f.input :title
    = f.label :description
    = f.rich_text_area :description

  .form-actions
    = f.button :submit
    
 

app/views/courses/edit.html.haml
.card
  .card-header
    %h1 Editing course
  .card.body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h3
  .text-center
    Courses
    // .badge.badge-info
    //   = @users.count
%p

.row
  .card-columns
    - @courses.each do |course|
      = render 'courses/course', course: course
  %br

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p
= render 'courses/course', course: @course

app/views/home/index.html.haml
.container-fluid.text-lg-left.p-5.bg-light
  .display-4
    Be Light Bee
    .fas.fa-lightbulb
  
  .p-4  

  .form-control.my-2.my-lg-5
    = form_tag(courses_path, method: :get) do
      .input-group
        = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}


.card-group
  .card.card-body
    %h2
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h2
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h2
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h2
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%hr
%h2
  Popular courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course

%hr
%h2 
  Top rated courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course

%hr
%h2 
  Recent courses
.card-columns
  - @recent_couses.each do |course|
    = render 'courses/course', course: course

%hr

  // = link_to privacy_policy_path, class: "btn btn-lg btn-warning" do
  //   %i.fa-solid.fa-video
  //   Videos
    
  // = link_to  courses_path, class: "btn btn-lg btn-warning" do
  //   %i.fa-solid.fa-book
  //   Courses

    

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'yashm@outlook.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-warning.container-fluid.justify-content-start
  %a.navbar-brand{:href => "/"} BLB
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user 
      %ul.navbar-nav.me-auto.container-fluid
        %li.nav-item.nav-link.active{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            // .fa.fa-home
            Home
        %li.nav-item.nav-link.active{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            // .fa.fa-book
            Courses
        %li.nav-item.nav-link.active{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            // .fa.fa-video
            Video
        %li.nav-item.nav-link.active{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item.nav-link.active{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
            
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'    
           
      .form-inline.my-2.my-lg-0.container-fluid.mr-end
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
                
                
    
      %ul.navbar-nav.mr-end    
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-end{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              // .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              // .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BLB
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    //initializing the application.scss
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/header'
    =render 'layouts/messages'
    .container
      %p
      = yield
    %br
    .bg-dark.text-white
      = render 'layouts/footer'

app/views/static_pages/landing_page.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fa-solid.fa-house
      BLB
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled Disabled
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container
  %h1 Be Light Bee
  // = link_to "Privacy Policy", privacy_policy_path, class: "btn btn-lg btn-warning"
  // = link_to privacy_policy_path, class: "btn btn-lg btn-warning" do
  //   %i.fa-solid.fa-video
  //   Videos
  = link_to "Privacy Policy", privacy_policy_path, class: "btn btn-lg btn-warning"
  = link_to courses_path, class: "btn btn-lg btn-warning" do
    %i.fa-solid.fa-video
    Videos
// .fa.fa-flag
// .fab.fa-amazon
// =link_to root_path do
//   .fa.fa-home
    
// =link_to courses_path, class: 'btn btn-success' do
//   .fa.fa-book
//   Course
    

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.email
  .card-footer
    Signed up
    = time_ago_in_words(user.created_at)
    ago
  .card-footer
    = 'sign_in_count'.humanize
    = user.sign_in_count
    .row
    = 'current_sign_in_at'.humanize
    = user.current_sign_in_at
    .row
    = 'last_sign_in_at'.humanize
    = user.last_sign_in_at
    .row
    = 'current_sign_in_ip'.humanize
    = user.current_sign_in_ip
    .row
    = 'last_sign_in_ip'.humanize
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .badge.badge-success Yes
    - else
      .badge.badge-danger No

app/views/users/index.html.haml
%h3
  .text-center
    Users
    .badge.badge-info
      = @users.count
%p

.card-columns
  -@users.each do |user|
    = render 'users/user', user: user